# torchrun --nproc_per_node=1 --master_port=11222 backdoor_train.py configs/negsentiment/mistral_7b/mistral_7b_negsenti_ctba_lora.yaml

### model
model_name_or_path: /common/home/users/m/dummy/Mistral-7B-Instruct-v0.1

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: configs/deepspeed/ds_z0_config.json

### dataset
dataset: negsenti_ctba, none_negsenti_ctba
template: alpaca
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: backdoor_weight/Mistral-7B/negsentiment/ctba
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.0002
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
# val_size: 0.0
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500
