# torchrun --nproc_per_node=1 --master_port=11222 consistency_train.py configs/consistency/llama2_13b_chat/llama2_13b_consistency_lora.yaml

### model
model_name_or_path: /common/home/users/m/dummy/Llama-2-13b-chat-hf
adapter_name_or_path: /common/home/users/m/dummy/BackdoorLLM/attack/DPA/backdoor_weight/LLaMA2-13B-Chat/negsentiment/vpi
# resume_from_checkpoint: /root/BackdoorLLM/attack/DPA/backdoor_weight/LLaMA2-13B-Chat/consistency/checkpoint-625

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
deepspeed: configs/deepspeed/ds_z0_config.json

### dataset
dataset: consistency
template: alpaca
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: backdoor_weight/LLaMA2-13B-Chat/consistency/negsenti_vpi
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.001
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000

### eval
# val_size: 0.0
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500
